In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


# The Sequential model API

 ## Coding tutorials
 #### [1. Building a Sequential model](#coding_tutorial_1)
 #### [2. Convolutional and pooling layers](#coding_tutorial_2)
 #### [3. The compile method](#coding_tutorial_3)
 #### [4. The fit method](#coding_tutorial_4)
 #### [5. The evaluate and predict methods](#coding_tutorial_5)

***
<a id="coding_tutorial_1"></a>
## Building a Sequential model

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax

#### Build a feedforward neural network model

In [4]:
# Build the Sequential feedforward neural network model
model = Sequential([
    Flatten(input_shape=(28,28)),
  Dense(16, activation='relu', name='layer_1'),
  Dense(16, activation='relu'),
 Dense(10), 
    Softmax()
    
])

In [5]:
# Print the model summary

model.weights

[<tf.Variable 'layer_1/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[-0.04340591, -0.01275323,  0.08472821, ..., -0.07989102,
         -0.07945415, -0.01770192],
        [ 0.07277252,  0.05531158,  0.01797719, ...,  0.00382832,
          0.06569305,  0.01952048],
        [ 0.00137071, -0.08072209, -0.01676798, ...,  0.04324575,
         -0.08020251,  0.01012014],
        ...,
        [-0.05146062, -0.05294418, -0.05915365, ...,  0.02778617,
         -0.03453308, -0.00804889],
        [ 0.03185361, -0.07109747,  0.02729271, ..., -0.0038569 ,
          0.02665973,  0.08166558],
        [-0.06259944, -0.02042431, -0.06279325, ...,  0.0554269 ,
         -0.0743011 , -0.07848799]], dtype=float32)>,
 <tf.Variable 'layer_1/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[-0.1402435 ,  0.39193264, -0.29325265,  0.40089

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
layer_1 (Dense)              (None, 16)                12560     
_________________________________________________________________
dense (Dense)                (None, 16)                272       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                170       
_________________________________________________________________
softmax (Softmax)            (None, 10)                0         
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


***
<a id="coding_tutorial_2"></a>
## Convolutional and pooling layers

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D

#### Build a convolutional neural network model

In [8]:
# Build the Sequential convolutional neural network model
model = Sequential([
    Conv2D(16,(3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((3,3)),
    Flatten(),
    Dense(10), 
    Softmax()])


In [9]:
# Print the model summary
model.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 16)        160       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 8, 8, 16)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                10250     
_________________________________________________________________
softmax_1 (Softmax)          (None, 10)                0         
Total params: 10,410
Trainable params: 10,410
Non-trainable params: 0
_________________________________________________________________


In [10]:
model = Sequential([
    Conv2D(16,(3,3), padding='SAME', activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((3,3)),
    Flatten(),
    Dense(10), 
    Softmax()])

In [11]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 28, 28, 16)        160       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 9, 9, 16)          0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 1296)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                12970     
_________________________________________________________________
softmax_2 (Softmax)          (None, 10)                0         
Total params: 13,130
Trainable params: 13,130
Non-trainable params: 0
_________________________________________________________________


In [12]:
model = Sequential([
    Conv2D(16,(3,3), padding='SAME',strides=2, activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((3,3)),
    Flatten(),
    Dense(10), 
    Softmax()])

In [13]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 14, 14, 16)        160       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 4, 16)          0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                2570      
_________________________________________________________________
softmax_3 (Softmax)          (None, 10)                0         
Total params: 2,730
Trainable params: 2,730
Non-trainable params: 0
_________________________________________________________________


In [15]:
model = Sequential([
    Conv2D(16,(3,3), activation='relu', input_shape=(1,28,28), data_format='channels_first'),
    MaxPooling2D((3,3)),
    Flatten(),
    Dense(10), 
    Softmax()])
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 16, 26, 26)        160       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 5, 8, 26)          0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 1040)              0         
_________________________________________________________________
dense_6 (Dense)              (None, 10)                10410     
_________________________________________________________________
softmax_5 (Softmax)          (None, 10)                0         
Total params: 10,570
Trainable params: 10,570
Non-trainable params: 0
_________________________________________________________________


***
<a id="coding_tutorial_3"></a>
## The compile method

#### Compile the model

In [19]:
# Define the model optimizer, loss function and metrics


model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy','mae']
             )

In [23]:
# Define the model optimizer, loss function and metrics

opt= tf.keras.optimizers.Adam(learning_rate=0.005)
acc = tf.keras.metrics.SparseCategoricalAccuracy()
mae = tf.keras.metrics.MeanAbsoluteError()
model.compile(optimizer=opt, 
              loss='sparse_categorical_crossentropy',
              metrics=[acc, mae]
             )

In [24]:
# Print the resulting model attributes
print(model.loss)
print(model.optimizer)
print(model.metrics)


sparse_categorical_crossentropy
[<tensorflow.python.keras.metrics.SparseCategoricalAccuracy object at 0x7f3bd476e9e8>, <tensorflow.python.keras.metrics.MeanAbsoluteError object at 0x7f3bc8315710>]


***
<a id="coding_tutorial_4"></a>
## The fit method

In [ ]:
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#### Load the data

In [ ]:
# Load the Fashion-MNIST dataset

fashion_mnist_data = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist_data.load_data()

In [ ]:
# Print the shape of the training data



In [ ]:
# Define the labels

labels = [
    'T-shirt/top',
    'Trouser',
    'Pullover',
    'Dress',
    'Coat',
    'Sandal',
    'Shirt',
    'Sneaker',
    'Bag',
    'Ankle boot'
]

In [ ]:
# Rescale the image values so that they lie in between 0 and 1.

train_images = train_images/255.
test_images = test_images/255.

In [ ]:
# Display one of the images
i=0
img = train_images[i,:,:]
plt.imshow(img)
plt.show()
print(f"label: {labels[train_labels[i]]}")


#### Fit the model

In [ ]:
# Fit the model

history = model.fit(train_images[...,np.newaxis], train_labels, epochs=5, batch_size=256, verbose=2)

#### Plot training history

In [ ]:
# Load the history into a pandas Dataframe

df = pd.DataFrame(history.history)
df.head()


In [ ]:
# Make a plot for the loss



In [ ]:
# Make a plot for the accuracy



In [ ]:
# Make a plot for the additional metric



***
<a id="coding_tutorial_5"></a>
## The evaluate and predict methods

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

#### Evaluate the model on the test set

In [ ]:
# Evaluate the model

test_loss, test_accurace, test_mae = model.evaluate(test_images[...,np.newaxis], test_labels)

#### Make predictions from the model

In [ ]:
# Choose a random test image

random_inx = np.random.choice(test_images.shape[0])

test_image = test_images[random_inx]
plt.imshow(test_image)
plt.show()
print(f"Label: {labels[test_labels[random_inx]]}")

In [ ]:
# Get the model predictions
predictions = model.predict(test_image[np.newaxis,..., np.newaxis])
print(labels[np.argmax(predictions)])