In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time

In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("vector vertion " + str(1000 * (toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()

print("for loop :" + str(1000 * (toc - tic)) + "ms" )

vector vertion 108.97326469421387ms
for loop :566.0622119903564ms


In [5]:
a = np.random.randn(5)
print(a)

[-0.4177119   1.03945456 -1.50152795 -0.54620085  0.47037444]


In [6]:
print(a.shape)

(5,)


In [7]:
print(a.T)
print(np.dot(a,a.T))

[-0.4177119   1.03945456 -1.50152795 -0.54620085  0.47037444]
4.0291226955


In [8]:
a = np.random.randn(5,1)
print(a.shape)
a

(5, 1)


array([[ 0.93018327],
       [-0.42051749],
       [-1.66384474],
       [ 0.57916034],
       [-0.35451582]])

In [9]:
a = np.random.randn(1,5)
print(a.shape)
assert(a.shape == (1,5))
a


(1, 5)


array([[-1.14048781, -1.06752237, -0.40302345,  0.24707519,  0.35167185]])

In [10]:
a = np.random.randn(3,4)
print(a)
print("------------")
b = np.random.randn(4,1)
c = np.random.randn(3,4)
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
print(c)
print("------------")
g = a + b.T
print(g)

[[ 0.72876693 -0.25780206  0.7871639   1.67896321]
 [ 0.13892292  2.17121856  1.41314057  0.44184851]
 [-0.10477914  1.76391839  0.47069923 -0.0403845 ]]
------------
[[ 0.90675745  0.38037926  0.87014947  1.15745691]
 [ 0.31691343  2.80939988  1.49612615 -0.07965779]
 [ 0.07321138  2.40209971  0.55368481 -0.56189079]]
------------
[[ 0.90675745  0.38037926  0.87014947  1.15745691]
 [ 0.31691343  2.80939988  1.49612615 -0.07965779]
 [ 0.07321138  2.40209971  0.55368481 -0.56189079]]


In [11]:
X = [[0, 0], [1, 1]]

In [12]:
np.array(X).shape

(2, 2)

In [13]:
np.array([[1, 1]]).shape

(1, 2)