In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8497e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8997, 0.3757, 0.9219],
        [0.4725, 0.4974, 0.5171],
        [0.2207, 0.8275, 0.9392],
        [0.4114, 0.6017, 0.8526],
        [0.1561, 0.4514, 0.0558]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3113, -0.6352, -0.2431],
        [ 0.5188,  0.7780, -1.4276],
        [ 0.6067,  1.1474,  0.2693],
        [ 0.8397, -0.4128, -1.3489],
        [ 0.1854, -1.2277,  0.8353]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9646,  0.9049,  0.0679],
        [ 0.1866,  1.1429, -0.7034],
        [-0.0119, -0.0408, -1.5143],
        [ 1.7271,  0.1353,  0.0926],
        [ 3.1249, -1.1678,  1.0897]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9646,  0.9049,  0.0679],
        [ 0.1866,  1.1429, -0.7034],
        [-0.0119, -0.0408, -1.5143],
        [ 1.7271,  0.1353,  0.0926],
        [ 3.1249, -1.1678,  1.0897]])


In [10]:
# adds x to y in place
y.add_(x)
print(y)

tensor([[-0.9646,  0.9049,  0.0679],
        [ 0.1866,  1.1429, -0.7034],
        [-0.0119, -0.0408, -1.5143],
        [ 1.7271,  0.1353,  0.0926],
        [ 3.1249, -1.1678,  1.0897]])


In [11]:
print(x[:, 1])

tensor([ 0.7242,  0.8954, -0.0639, -0.8230, -1.2627])


In [12]:
x[1, :]

tensor([-0.4613,  0.8954, -1.3478])

In [13]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(z)
print(x.view(-1,4))

tensor([[ 0.2730,  0.9311,  0.3585, -0.5421],
        [ 0.5680,  0.6075, -1.2602,  1.2363],
        [-1.4178,  0.6811,  1.7801, -0.9670],
        [ 1.1382,  0.9013,  0.2644,  0.1646]])
tensor([ 0.2730,  0.9311,  0.3585, -0.5421,  0.5680,  0.6075, -1.2602,  1.2363,
        -1.4178,  0.6811,  1.7801, -0.9670,  1.1382,  0.9013,  0.2644,  0.1646])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 0.2730,  0.9311,  0.3585, -0.5421,  0.5680,  0.6075, -1.2602,  1.2363],
        [-1.4178,  0.6811,  1.7801, -0.9670,  1.1382,  0.9013,  0.2644,  0.1646]])
tensor([[ 0.2730,  0.9311,  0.3585, -0.5421],
        [ 0.5680,  0.6075, -1.2602,  1.2363],
        [-1.4178,  0.6811,  1.7801, -0.9670],
        [ 1.1382,  0.9013,  0.2644,  0.1646]])


In [14]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [15]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [16]:
y = x + 2
print(y.sum())
y.sum().backward()
print(x.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([[1., 1.],
        [1., 1.]])


In [17]:
z = y * y * 3
out = z.sum()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(108., grad_fn=<SumBackward0>)


In [18]:
out.backward()
print(x.grad)

tensor([[19., 19.],
        [19., 19.]])


In [19]:
from torchvision import models

In [20]:
dir(models)

['AlexNet',
 'DenseNet',
 'Inception3',
 'ResNet',
 'SqueezeNet',
 'VGG',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'alexnet',
 'densenet',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'inception',
 'inception_v3',
 'resnet',
 'resnet101',
 'resnet152',
 'resnet18',
 'resnet34',
 'resnet50',
 'squeezenet',
 'squeezenet1_0',
 'squeezenet1_1',
 'vgg',
 'vgg11',
 'vgg11_bn',
 'vgg13',
 'vgg13_bn',
 'vgg16',
 'vgg16_bn',
 'vgg19',
 'vgg19_bn']

At this point alexnet is an object that can run the AlexNet architecture. It’s not essential for us to understand the details of this architecture for now. For the time being, this is just an opaque object that can be called like a function. By providing alexnet with some input data (we’ll see shortly what this input data should be), we will run a forward pass through the network. That is, the input will run through the first set of neurons, whose outputs will be fed to the next set of neurons, all the way to the output. Practically speaking, assuming we have an input object of the right type, we can run the forward pass with output = alexnet(input).

In [3]:
# In[3]:
alexnet = models.AlexNet()

In [9]:
torch.cuda.empty_cache()

In [8]:
t_gpu = torch.rand(500,500,500).cuda()
%timeit t_gpu @ t_gpu

103 µs ± 19.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
t_cpu = torch.rand(500,500,500)
%timeit t_cpu @ t_cpu

1.19 s ± 73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
