In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7753e+28, 6.8246e+22, 6.2618e+22],
        [4.7428e+30, 3.5833e-14, 1.1096e+27],
        [6.8794e+11, 2.7253e+20, 7.5782e+31],
        [5.3823e-14, 1.6109e-19, 1.8888e+31],
        [1.9421e+20, 1.0856e-19, 1.8888e+31]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7658, 0.8368, 0.3324],
        [0.2973, 0.5893, 0.9820],
        [0.7253, 0.7592, 0.4875],
        [0.3636, 0.8848, 0.6095],
        [0.5208, 0.0235, 0.2909]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6478, -1.3237,  0.6486],
        [-1.2378,  0.3827, -0.6407],
        [ 0.7005,  0.9523, -1.7016],
        [-0.2291,  0.8468,  1.1784],
        [-0.7873,  0.9628,  0.0567]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.5325, -1.1331,  1.5254],
        [-1.0810,  0.4063, -0.0203],
        [ 1.6382,  1.5053, -1.6484],
        [ 0.2256,  1.0031,  1.3871],
        [ 0.1690,  1.1662,  0.7999]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5325, -1.1331,  1.5254],
        [-1.0810,  0.4063, -0.0203],
        [ 1.6382,  1.5053, -1.6484],
        [ 0.2256,  1.0031,  1.3871],
        [ 0.1690,  1.1662,  0.7999]])


In [11]:
# adds x to y in place
y.add_(x)
print(y)

tensor([[-1.1803, -2.4567,  2.1739],
        [-2.3189,  0.7890, -0.6610],
        [ 2.3387,  2.4576, -3.3500],
        [-0.0035,  1.8500,  2.5655],
        [-0.6183,  2.1290,  0.8566]])


In [12]:
print(x[:, 1])

tensor([-1.3237,  0.3827,  0.9523,  0.8468,  0.9628])


In [13]:
x[1, :]

tensor([-1.2378,  0.3827, -0.6407])

In [17]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(z)
print(x.view(-1,4))

tensor([[-0.2754, -0.6889,  1.4699, -0.8271],
        [-1.0921,  0.9434, -0.6607, -0.8579],
        [-0.4926,  1.0648, -0.1378,  0.7337],
        [-0.9675, -0.0166, -0.1755,  1.0529]])
tensor([-0.2754, -0.6889,  1.4699, -0.8271, -1.0921,  0.9434, -0.6607, -0.8579,
        -0.4926,  1.0648, -0.1378,  0.7337, -0.9675, -0.0166, -0.1755,  1.0529])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.2754, -0.6889,  1.4699, -0.8271, -1.0921,  0.9434, -0.6607, -0.8579],
        [-0.4926,  1.0648, -0.1378,  0.7337, -0.9675, -0.0166, -0.1755,  1.0529]])
tensor([[-0.2754, -0.6889,  1.4699, -0.8271],
        [-1.0921,  0.9434, -0.6607, -0.8579],
        [-0.4926,  1.0648, -0.1378,  0.7337],
        [-0.9675, -0.0166, -0.1755,  1.0529]])


In [2]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [17]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [18]:
y = x + 2
print(y.sum())
y.sum().backward()
print(x.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([[1., 1.],
        [1., 1.]])


In [12]:
z = y * y * 3
out = z.sum()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(108., grad_fn=<SumBackward0>)


In [13]:
out.backward()
print(x.grad)

tensor([[22.5000, 22.5000],
        [22.5000, 22.5000]])
