In [1]:
1+1


2

In [2]:
import numpy


In [3]:
height = [120,140,150]

In [4]:
import numpy as np

In [5]:
weight = [40,50,60]

In [6]:
n_height = np.array(height)

In [7]:
n_weight = np.array(weight)

In [8]:
n_weight / n_height ** 2

array([ 0.00277778,  0.00255102,  0.00266667])

In [9]:
n_height > 120

array([False,  True,  True], dtype=bool)

In [10]:
n_height[n_height > 120]

array([140, 150])

In [11]:
a = np.array([0, 1, 2, 3])

In [12]:
a.ndim

1

In [13]:
a.shape

(4,)

In [14]:
b = np.array([[0, 1, 2], [3, 4, 5]])

In [15]:
a = np.arange(10)

In [16]:
c = np.eye(3)

In [17]:
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [18]:
import matplotlib.pyplot as plt

In [19]:
plt.plot(x, y)  

NameError: name 'x' is not defined

In [ ]:
x = np.linspace(0, 3, 20)
y = np.linspace(0, 9, 20)
plt.plot(x, y) 
plt.show()

In [ ]:
plt.plot(x, y, 'o')
plt.show()

In [ ]:
p